name: TotemGuard

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'TotemGuard'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - totemguard:/var/lib/mysql

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    expose:
      - '6379'
    volumes:
      - totemguard:/data

volumes:
  totemguard: