name: TotemGuard
version: ${version}
main: com.deathmotion.totemguard.TotemGuard
loader: com.deathmotion.totemguard.bootstrap.TotemGuardLoader
api-version: '1.19'
folia-supported: true
authors: [ Bram, OutDev ]
description: ${description}
load: POSTWORLD
dependencies:
  server:
    packetevents:
      load: BEFORE
      required: true
      join-classpath: true