name: TotemGuard
version: ${version}
main: com.deathmotion.totemguard.TotemGuard
api-version: '1.20'
folia-supported: true
authors: [ Bram, OutDev ]
description: TotemGuard is a simple anti-cheat that tries to detect players who are using AutoTotem.
load: POSTWORLD
libraries:
  - io.ebean:ebean-core:${ebeanVersion}
  - io.ebean:ebean-sqlite:${ebeanVersion}
  - io.ebean:ebean-mysql:${ebeanVersion}
  - de.exlll:configlib-yaml:${configlibVersion}
  - de.exlll:configlib-paper:${configlibVersion}
  - club.minnced:discord-webhooks:${discordWebhooksVersion}
depend:
  - packetevents
softdepend:
  - BetterReload
permissions:
  TotemGuard.*:
    description: Gives access to all TotemGuard permissions.
    default: op
    children:
      TotemGuard.Reload: true
      TotemGuard.Check: true
      TotemGuard.Alerts: true
      TotemGuard.Alerts.Others: true
      TotemGuard.Bypass: true
      TotemGuard.Update: true
  TotemGuard.Reload:
    description: Allows the player to use /totemguard reload.
    default: op
  TotemGuard.Check:
    description: Allows the player to use the /check command.
    default: op
  TotemGuard.Alerts:
    description: Allows the player to use /totemguard alerts.
    default: op
  TotemGuard.Alerts.Others:
    description: Allows the player to use /totemguard alerts <player>.
    default: op
  TotemGuard.Bypass:
    description: Allows the player to bypass the checks.
    default: op
  TotemGuard.Update:
    description: Allows the player to receive update notifications.
    default: true
  TotemGuard.Debug:
    description: Allows the player to see debug messages.
    default: false
commands:
  TotemGuard:
    description: Base command for TotemGuard.
    aliases:
      - tg
  Check:
    description: Checks a player for manually for AutoTotem.
    aliases:
      - totemcheck
      - checktotem
