name: TotemGuard
version: ${version}
main: com.deathmotion.totemguard.TotemGuard
api-version: '1.16'
folia-supported: true
authors: [ Bram, OutDev ]
description: ${description}
load: POSTWORLD
depend:
  - packetevents
libraries:
  - de.exlll:configlib-paper:${configlibVersion}