name: TotemGuard
version: ${version}
main: com.deathmotion.totemguard.TotemGuard
api-version: '1.16'
folia-supported: true
authors: [ Bram, OutDev ]
description: TotemGuard is a simple anti-cheat that tries to detect players who are using AutoTotem.
load: POSTWORLD
depend:
  - packetevents
permissions:
  TotemGuard.*:
    description: Gives access to all TotemGuard permissions.
    default: op
    children:
      TotemGuard.Reload: true
      TotemGuard.Check: true
      TotemGuard.Alerts: true
      TotemGuard.Alerts.Others: true
      TotemGuard.Profile: true
      TotemGuard.Stats: true
      TotemGuard.ClearLogs: true
      TotemGuard.Bypass: true
      TotemGuard.Update: true
      TotemGuard.Top: true
      TotemGuard.ManualBan: true
      TotemGuard.Database.*: true
  TotemGuard.Staff:
    description: Gives access to all TotemGuard Staff permissions.
    default: op
    children:
      TotemGuard.Check: true
      TotemGuard.Alerts: true
      TotemGuard.Profile: true
  TotemGuard.Database.*:
    description: Gives access to all TotemGuard Database permissions.
    default: op
    children:
      TotemGuard.Database.Trim: true
      TotemGuard.Database.Clear: true
  TotemGuard.Reload:
    description: Allows the player to use /totemguard reload.
    default: op
  TotemGuard.Check:
    description: Allows the player to use /totemguard check.
    default: op
  TotemGuard.Alerts:
    description: Allows the player to use /totemguard alerts.
    default: op
  TotemGuard.Alerts.Others:
    description: Allows the player to use /totemguard alerts <player>.
    default: op
  TotemGuard.Profile:
    description: Allows the player to use /totemguard profile.
    default: op
  TotemGuard.Stats:
    description: Allows the player to use /totemguard stats.
    default: op
  TotemGuard.ClearLogs:
    description: Allows the player to clear the logs of a player.
    default: op
  TotemGuard.Track:
    description: Allows the player to track a player.
    default: op
  TotemGuard.Bypass:
    description: Allows the player to bypass the checks.
    default: op
  TotemGuard.Update:
    description: Allows the player to receive update notifications.
    default: op
  TotemGuard.Top:
    description: Allows the player to see the top players based on violations.
    default: op
  TotemGuard.ManualBan:
    description: Allows the player to manually ban a player as if banned by TotemGuard.
    default: op
  TotemGuard.Database.Trim:
    description: Allows the player to trim the database.
    default: op
  TotemGuard.Database.Clear:
    description: Allows the player to clear the database.
    default: op
  TotemGuard.Debug:
    description: Allows the player to see debug messages.
    default: false