name: TotemGuard
version: ${version}
main: com.deathmotion.totemguard.TotemGuard
api-version: '1.16'
folia-supported: true
authors: [ Bram, OutDev ]
description: ${description}
load: POSTWORLD
depend:
  - packetevents
libraries:
  - de.exlll:configlib-paper:${configlibVersion}
  - club.minnced:discord-webhooks:${discordWebhooksVersion}
  - io.lettuce:lettuce-core:${lettuceVersion}
  - dev.jorel:commandapi-bukkit-shade:${commandapiVersion}
  - net.jodah:expiringmap:${expiringmapVersion}
  - org.hibernate:hibernate-core:${hibernateVersion}
  - mysql:mysql-connector-java:${mysqlConnectorVersion}
  - com.h2database:h2:${h2Version}