package version

import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction
import org.gradle.work.DisableCachingByDefault

@DisableCachingByDefault(because = "The generated source embeds the current build timestamp.")
abstract class TGVersionTask : DefaultTask() {

    companion object {
        const val TASK_NAME = "generateVersionsFile"
        private val VERSION_PATTERN = Regex("""(\d+)\.(\d+)\.(\d+)(?:(?:\+([0-9a-f]+))?-SNAPSHOT)?""")
    }

    @get:Input
    abstract val packageName: Property<String>

    @get:Input
    abstract val className: Property<String>

    @get:Input
    abstract val versionValue: Property<String>

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @TaskAction
    fun generate() {
        val packagePath = packageName.get().replace('.', '/')
        val cls = className.get()
        val file = outputDir.file("$packagePath/$cls.java").get().asFile
        file.parentFile.mkdirs()

        val version = versionValue.get()
        val parsedVersion = parseVersion(version)

        file.writeText(
            """
            /**
             * This file is generated by the build. Modifying it will have no effect.
             */
            package ${packageName.get()};

            import com.deathmotion.totemguard.api.versioning.TGVersion;

            import java.time.Instant;

            public final class $cls {

                public static final String RAW = "$version";
                public static final Instant BUILD_TIMESTAMP = Instant.ofEpochMilli(${System.currentTimeMillis()}L);
                public static final TGVersion CURRENT = new TGVersion(${parsedVersion.major}, ${parsedVersion.minor}, ${parsedVersion.patch}, ${parsedVersion.snapshot}, ${parsedVersion.quotedSnapshotCommit()});
                public static final TGVersion UNKNOWN = new TGVersion(0, 0, 0);

                private $cls() {
                    throw new IllegalStateException();
                }
            }
            """.trimIndent()
        )
    }

    private fun parseVersion(version: String): ParsedVersion {
        val match = VERSION_PATTERN.matchEntire(version)
            ?: throw IllegalArgumentException("Invalid version: $version")

        return ParsedVersion(
            major = match.groupValues[1].toInt(),
            minor = match.groupValues[2].toInt(),
            patch = match.groupValues[3].toInt(),
            snapshot = version.endsWith("-SNAPSHOT"),
            snapshotCommit = match.groupValues[4].ifEmpty { null }
        )
    }

    private data class ParsedVersion(
        val major: Int,
        val minor: Int,
        val patch: Int,
        val snapshot: Boolean,
        val snapshotCommit: String?
    ) {
        fun quotedSnapshotCommit(): String {
            return snapshotCommit?.let { "\"$it\"" } ?: "null"
        }
    }
}
