name: TotemGuardV3
authors:
  - Bram
  - OutDev
main: com.deathmotion.totemguard.bukkit.TGBukkit
version: ${version}
api-version: '1.13'
folia-supported: true
load: POSTWORLD
depend:
  - packetevents
softdepend:
  - PlaceholderAPI