name: APITestPlugin
version: ${version}
main: com.deathmotion.totemguard.testplugin.ApiTestPlugin
api-version: '1.21'
dependencies:
  server:
    TotemGuard:
      load: BEFORE
      required: true
      join-classpath: true
