name: APITestPlugin
version: ${version}
main: com.deathmotion.totemguard.testplugin.ApiTestPlugin
api-version: '1.20'
dependencies:
  server:
    TotemGuard:
      load: BEFORE
      required: false
      join-classpath: true
