name: APITestPlugin
version: ${version}
main: com.deathmotion.totemguard.testplugin.ApiTestPlugin
api-version: '1.21'
folia-supported: true
author: Bram
description: A simple test plugin for the TotemGuard API.
load: POSTWORLD
softdepend:
  - TotemGuard