#    ___________     __                   ________                       .___
#    \__    ___/____/  |_  ____   _____  /  _____/ __ _______ _______  __| _/
#      |    | /  _ \   __\/ __ \ /     \/   \  ___|  |  \__  \\_  __ \/ __ |
#      |    |(  <_> )  | \  ___/|  Y Y  \    \_\  \  |  // __ \|  | \/ /_/ |
#      |____| \____/|__|  \___  >__|_|  /\______  /____/(____  /__|  \____ |
#                             \/      \/        \/           \/           \/

# The version of the config file. DO NOT TOUCH!!!
config_version: 1

# The name of the root command for TotemGuard. (This requires a server restart to take effect)
commands:
  base: totemguard3
  aliases:
    - tg3

# In a multiserver setup, enabling Redis is highly recommended.
# Redis will make TotemGuard much more powerful by syncing data, alerts and more across servers.
redis:
  enabled: false
  host: localhost
  port: 6379

  # Can be left empty if no auth is required.
  username: default
  password: yourPassword

  # Alert Sync
  messaging:
    channel: totemguard
    send-alerts: true
    receive-alerts: true

# Caches information like check violations, buffers, and other player data.
# This prevents a cheater from quickly leaving and rejoining the server to clear their active violations.
# Note: When Redis is enabled, this will be synced across servers.
cache:
  # Enable caching.
  enabled: true

  # How long to cache data for in seconds (0 = no caching).
  data:
    # Includes violations and buffers.
    checks: 300
    # Alerts toggle state.
    alerts-toggle: 1800
    # VPN data (prevents making unessecary API calls by caching the result)
    vpn-data: 1800

  local:
    # Maximum amount of local fallback entries kept in-memory.
    max-entries: 10000

# Enables the Anti-VPN Detection feature.
anti-vpn:
  # Enable VPN detection.
  enabled: true

  # The Anti VPN provider to use. (IPRisk, etc)
  provider: IPRisk

  # The API key to use for the VPN provider (can leave blank or default if the provider doesn't require one)'.
  api-key:

  # Whether to block VPN users from joining the server.
  block: true